// vue-ui/src/App.vue
<!--
 * @description: 
 * @author: xiejiaxin
 * @e-mail: xiejx@glodon.com
 * @Date: 2022-02-23 16:05:34
 * @desc: 
-->
<template>
  <h1>vue</h1>
</template>

<script>

export default {
  name: 'App'
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react-ui/src/App.js
/*
 * @description: 
 * @author: xiejiaxin
 * @e-mail: xiejx@glodon.com
 * @Date: 2022-02-23 16:12:48
 * @desc: 
 */
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>react</h1>
      </header>
    </div>
  );
}

export default App;
